### PR TITLE
standardise the colour state command payload to match config/status payloads

### PR DESCRIPTION
**Pull request by sumnerboy12**

### CODE REVIEW

**Comment by moinmoin-sh** [comment]
Just thinking if we should shorten the color names throughout to "r", "g" and "b". Should be clear enough but reduces the payloads.

**Comment by sumnerboy12** [comment]
I don't mind either way, but happy to change. Shall I do it in this PR?

**Comment by moinmoin-sh** [comment]
Yes, I think so. Best time to do it. (another braking change)

**Comment by sumnerboy12** [comment]
Should we also rename color_temperature to color_kelvin?

Explicit is always good.

**Comment by plains203** [comment]
> Should we also rename color_temperature to color_kelvin?
> 
> Explicit is always good. 

I would agree with that

**Comment by moinmoin-sh** [comment]
do you mean `colorKelvin `?

**Comment by sumnerboy12** [comment]
Yes I did, as soon as I sent that I realized my mistake.

**Comment by sumnerboy12** [comment]
Updated as requested.

**Comment by sumnerboy12** [comment]
@moinmoin-sh are you happy with these changes? is it going to cause conflicts with your changes to the color picker stuff?

**Comment by moinmoin-sh** [comment]
Yes, sorry for not replying. The changes in the colorPicker are masive and I would like to finish that before merging other stuff.
Please let's do this tidy up later.

**Comment by sumnerboy12** [comment]
Yep thought that would be the case. I'll hold off till you merge your stuff and I'll reapply these changes.

**Comment by sumnerboy12** [comment]
@moinmoin-sh have rebased your colour picker changes and updated this PR. Would you mind running your eye over it again?

**Review by moinmoin-sh — APPROVED** [review]
Please remember to update our documentation (to do list) as required.

**Pull request merged**
